root: true
settings:
  react:
    version: "detect"
  import/parsers:
    "@typescript-eslint/parser": [".ts", ".tsx"]
  import/resolver:
    typescript: true
    node: true
env:
  browser: true
  es2020: true
parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react-hooks/recommended"
  # https://github.com/import-js/eslint-plugin-import
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "prettier"
plugins: ["@typescript-eslint"]
parserOptions:
  sourceType: "module"
  ecmaVersion: 2020
rules:
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/consistent-type-imports": "error"
  "import/no-named-as-default": "off"
  "import/order":
    - "error"
    - newlines-between: "always"
      alphabetize:
        order: "asc"
        caseInsensitive: true
